const WHATSAPP='96171546495';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const variants={
  'Black / White':[
    'assets/products/IMG_0441.jpg','assets/products/IMG_0443.jpg','assets/products/IMG_0444.jpg','assets/products/IMG_0447.png','assets/products/IMG_0448.png','assets/products/IMG_0450.png','assets/products/IMG_0451.png'
  ],
  'White':[
    'assets/products/IMG_0452.png','assets/products/IMG_0453.png'
  ]
};
const product={id:'nb-530',name:'New Balance 530',brand:'New Balance',category:'Sneakers',price:0,new_drop:true,sold_out:false,sizes:['37','38','39','40','41'],description:'Chunky everyday sneaker with a breathable upper. Choose your color and size.',variants};
function readCart(){try{const v=JSON.parse(localStorage.getItem('sharif-cart')||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
const state={products:[product],cart:readCart(),filter:'all'};
function safeText(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function money(v){return Number(v)>0?`$${Number(v).toFixed(2)}`:'Price on WhatsApp'}
function waLink(text){return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`}
function lock(){document.body.classList.toggle('no-scroll',$('#cartDrawer').classList.contains('open')||$('#productModal').open||$('#searchModal').open)}
function renderProducts(){const list=state.filter==='sale'?[]:state.products;$('#products').innerHTML=list.map(p=>`<article class="product-card" role="button" tabindex="0"><div class="product-image-wrap"><img src="${p.variants['Black / White'][0]}" alt="${safeText(p.name)}"><span class="badge">NEW DROP</span><span class="photo-count">2 colors</span></div><div class="product-info"><div><h3>${safeText(p.name)}</h3><p>Black / White · White · Sizes 37–41</p></div><div class="product-price">${money(p.price)}</div></div></article>`).join('')||'<div class="empty">Nothing in this section right now.</div>';$$('.product-card').forEach(el=>{el.onclick=openProduct;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProduct()}}})}
function openProduct(){const p=product;let color='Black / White',imgs=p.variants[color],index=0,selectedSize='';$('#modalContent').innerHTML=`<div class="modal-layout"><div class="gallery"><div class="main-photo" id="mainPhotoArea"><button class="gallery-arrow prev" id="galleryPrev">‹</button><img id="modalMainImage" src="${imgs[0]}" alt="${p.name}"><button class="gallery-arrow next" id="galleryNext">›</button><span class="gallery-counter" id="galleryCounter">1 / ${imgs.length}</span></div><div class="thumbs" id="galleryThumbs"></div></div><div class="modal-details"><p class="eyebrow">NEW BALANCE</p><h2>${p.name}</h2><div class="product-price modal-price">${money(p.price)}</div><p class="desc">${p.description}</p><div class="size-block"><div class="size-label"><p class="eyebrow">SELECT COLOR</p><span id="colorHint">${color}</span></div><div class="size-grid" id="colorGrid">${Object.keys(p.variants).map((v,i)=>`<button class="size-btn color-btn ${i===0?'active':''}" data-color="${v}">${v}</button>`).join('')}</div></div><div class="size-block"><div class="size-label"><p class="eyebrow">SELECT SIZE</p><span id="sizeHint">37–41 available</span></div><div class="size-grid">${p.sizes.map(s=>`<button class="size-btn size-choice" data-size="${s}">${s}</button>`).join('')}</div></div><div class="modal-actions"><button id="addToBag" class="primary-btn full">Add to bag <span>+</span></button><button id="directWhatsApp" class="secondary-btn full">Ask on WhatsApp <span>↗</span></button></div></div></div>`;
const renderGallery=()=>{$('#modalMainImage').src=imgs[index];$('#galleryCounter').textContent=`${index+1} / ${imgs.length}`;$('#galleryThumbs').innerHTML=imgs.map((src,n)=>`<button class="thumb ${n===index?'active':''}" data-index="${n}"><img src="${src}" alt="${p.name} ${color} photo ${n+1}"></button>`).join('');$$('.thumb').forEach(t=>t.onclick=()=>{index=Number(t.dataset.index);renderGallery()})};
const setImage=n=>{index=(n+imgs.length)%imgs.length;renderGallery()};renderGallery();
$('#galleryPrev').onclick=()=>setImage(index-1);$('#galleryNext').onclick=()=>setImage(index+1);let sx=0;const area=$('#mainPhotoArea');area.addEventListener('pointerdown',e=>sx=e.clientX);area.addEventListener('pointerup',e=>{const d=e.clientX-sx;if(Math.abs(d)>45)setImage(index+(d<0?1:-1))});
$$('.color-btn').forEach(b=>b.onclick=()=>{color=b.dataset.color;imgs=p.variants[color];index=0;$$('.color-btn').forEach(x=>x.classList.toggle('active',x===b));$('#colorHint').textContent=color;renderGallery()});
$$('.size-choice').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;$$('.size-choice').forEach(x=>x.classList.toggle('active',x===b));$('#sizeHint').textContent=`Size ${selectedSize} selected`});
$('#addToBag').onclick=()=>{if(!selectedSize){$('#sizeHint').textContent='Choose a size first';return}const ex=state.cart.find(x=>x.id===p.id&&x.size===selectedSize&&x.color===color);if(ex)ex.qty=Math.min(9,(ex.qty||1)+1);else state.cart.push({id:p.id,size:selectedSize,color,qty:1});saveCart();$('#productModal').close();openCart()};$('#directWhatsApp').onclick=()=>window.open(waLink(`Hi Sharif Store, I want to ask about ${p.name} — ${color}${selectedSize?` — size ${selectedSize}`:''}.`),'_blank','noopener');$('#productModal').showModal();lock()}
function saveCart(){localStorage.setItem('sharif-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){$('#cartCount').textContent=state.cart.reduce((a,x)=>a+(x.qty||1),0);$('#cartItems').innerHTML=state.cart.length?state.cart.map((x,n)=>`<div class="cart-row"><img src="${product.variants[x.color||'Black / White'][0]}" alt="${product.name}"><div class="cart-copy"><h4>${product.name}</h4><p>${x.color||'Black / White'} · Size ${x.size}</p><strong>${money(product.price)}</strong><div class="qty-control"><button data-index="${n}" data-delta="-1">−</button><span>${x.qty||1}</span><button data-index="${n}" data-delta="1">+</button></div></div><button class="remove-btn" data-index="${n}">×</button></div>`).join(''):'<div class="empty bag-empty"><b>Your bag is empty.</b><span>Pick a color and choose your size.</span></div>';$$('.qty-control button').forEach(b=>b.onclick=()=>{const i=+b.dataset.index,d=+b.dataset.delta;state.cart[i].qty=Math.max(0,Math.min(9,(state.cart[i].qty||1)+d));if(!state.cart[i].qty)state.cart.splice(i,1);saveCart()});$$('.remove-btn').forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.index,1);saveCart()});$('#checkoutBtn').disabled=!state.cart.length}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');$('#backdrop').classList.add('show');lock()}function closeCart(){$('#cartDrawer').classList.remove('open');$('#backdrop').classList.remove('show');lock()}
$('#checkoutBtn').onclick=()=>{if(!state.cart.length)return;const lines=['SHARIF STORE — ORDER REQUEST',''];state.cart.forEach(x=>lines.push(`${product.name} — ${x.color||'Black / White'} — Size ${x.size} — Qty ${x.qty||1}`));lines.push('','Please confirm availability and delivery price.');window.open(waLink(lines.join('\n')),'_blank','noopener')};$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#backdrop').onclick=closeCart;$('#modalClose').onclick=()=>$('#productModal').close();$('#productModal').addEventListener('close',lock);$('#searchBtn').onclick=()=>{$('#searchModal').showModal();lock();setTimeout(()=>$('#searchInput').focus(),30)};$('#searchClose').onclick=()=>$('#searchModal').close();$('#searchModal').addEventListener('close',lock);$('#searchInput').oninput=e=>{$('#searchResults').innerHTML=e.target.value.trim()?`<button class="search-result"><span>${product.name}</span><b>${money(product.price)}</b></button>`:'';$('.search-result')?.addEventListener('click',()=>{$('#searchModal').close();openProduct()})};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderProducts()});$('#footerWhatsApp').href=waLink('Hi Sharif Store, I have a question.');$('#heroImage').src=product.variants['Black / White'][0];$('#heroImage').classList.add('ready');renderProducts();renderCart();