const SUPABASE_URL='https://uogsmczhjbcseysvosom.supabase.co';
const SUPABASE_KEY='sb_publishable_57YHVi_GpOtu6mOeZqXQXA_6hqSzERa';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const WHATSAPP='96171546495';
const state={products:[],cart:JSON.parse(localStorage.getItem('sharif-cart')||'[]'),filter:'all'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function asset(u){if(!u)return''; if(/^https?:/.test(u))return u; return new URL(u,document.baseURI).href}
function money(v){return Number(v)>0?`$${Number(v).toFixed(Number(v)%1?2:0)}`:'Price on WhatsApp'}
async function loadProducts(){const {data,error}=await sb.from('products').select('*,product_images(*)').order('position');if(error){console.error(error);return}state.products=(data||[]).map(p=>({...p,product_images:(p.product_images||[]).sort((a,b)=>a.sort_order-b.sort_order)}));renderProducts();const first=state.products[0];if(first?.product_images?.[0])$('#heroImage').src=asset(first.product_images[0].image_url)}
function renderProducts(list=state.products){let p=list;if(state.filter==='new')p=p.filter(x=>x.new_drop);if(state.filter==='sale')p=p.filter(x=>x.on_sale);$('#products').innerHTML=p.map(card).join('')||'<div class="empty">No products in this section yet.</div>';$$('.product-card').forEach(el=>el.onclick=()=>openProduct(el.dataset.id))}
function card(p){const img=asset(p.product_images?.[0]?.image_url);return `<article class="product-card" data-id="${p.id}"><div class="product-image-wrap"><img loading="lazy" src="${img}" alt="${p.name}">${p.sold_out?'<span class="badge sold-badge">SOLD OUT</span>':p.new_drop?'<span class="badge">NEW DROP</span>':''}</div><div class="product-info"><div><h3>${p.name}</h3><p>${p.brand} · ${p.category}</p></div><div class="product-price">${money(p.price)}</div></div></article>`}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;let selectedSize=p.sizes?.[0]||'';const imgs=p.product_images||[];$('#modalContent').innerHTML=`<div class="modal-layout"><div class="gallery"><div class="thumbs">${imgs.map((i,n)=>`<button class="thumb ${n===0?'active':''}" data-img="${asset(i.image_url)}"><img src="${asset(i.image_url)}" alt="${i.alt_text||p.name}"></button>`).join('')}</div><div class="main-photo"><img id="modalMainImage" src="${asset(imgs[0]?.image_url||'')}" alt="${p.name}"></div></div><div class="modal-details"><p class="eyebrow">${p.brand}</p><h2>${p.name}</h2><div class="product-price" style="font-size:20px;margin-bottom:18px">${money(p.price)}</div><p class="desc">${p.description||'A clean everyday sneaker selected by Sharif Store for shape, comfort and easy styling.'}</p><p class="eyebrow" style="margin-top:28px">SELECT SIZE</p><div class="size-grid">${(p.sizes||[]).map((s,n)=>`<button class="size-btn ${n===0?'active':''}" data-size="${s}">${s}</button>`).join('')}</div><button id="addToBag" class="primary-btn full" ${p.sold_out?'disabled':''}>${p.sold_out?'Sold out':'Add to bag'} <span>+</span></button><button id="directWhatsApp" class="primary-btn full" style="margin-top:10px;background:#eceae4;color:#0b0b0c">Ask on WhatsApp <span>↗</span></button></div></div>`;
$$('.thumb').forEach(t=>t.onclick=()=>{$$('.thumb').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#modalMainImage').src=t.dataset.img});$$('.size-btn').forEach(b=>b.onclick=()=>{$$('.size-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedSize=b.dataset.size});
const add=$('#addToBag');if(add&&!p.sold_out)add.onclick=()=>{state.cart.push({id:p.id,size:selectedSize,qty:1});saveCart();$('#productModal').close();openCart()};$('#directWhatsApp').onclick=()=>window.open(waLink(`Hi Sharif Store, I want to ask about ${p.name}${selectedSize?` in size ${selectedSize}`:''}.`),'_blank');$('#productModal').showModal()}
function saveCart(){localStorage.setItem('sharif-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){$('#cartCount').textContent=state.cart.reduce((a,x)=>a+x.qty,0);$('#cartItems').innerHTML=state.cart.length?state.cart.map((x,n)=>{const p=state.products.find(z=>z.id===x.id);if(!p)return'';return `<div class="cart-row"><img src="${asset(p.product_images?.[0]?.image_url)}" alt="${p.name}"><div><h4>${p.name}</h4><p>Size ${x.size} · Qty ${x.qty}</p><strong>${money(p.price)}</strong></div><button class="remove-btn" data-index="${n}">×</button></div>`}).join(''):'<div class="empty">Your bag is empty.</div>';$$('.remove-btn').forEach(b=>b.onclick=()=>{state.cart.splice(Number(b.dataset.index),1);saveCart()})}
function openCart(){renderCart();$('#cartDrawer').classList.add('open');$('#backdrop').classList.add('show');$('#cartDrawer').setAttribute('aria-hidden','false')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#backdrop').classList.remove('show');$('#cartDrawer').setAttribute('aria-hidden','true')}
function waLink(text){return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`}
$('#checkoutBtn').onclick=()=>{if(!state.cart.length)return;const lines=['SHARIF STORE — ORDER REQUEST',''];state.cart.forEach(x=>{const p=state.products.find(z=>z.id===x.id);if(p)lines.push(`${p.name} — Size ${x.size} — Qty ${x.qty}`)});lines.push('','Please confirm availability and delivery price.');window.open(waLink(lines.join('\n')),'_blank')};
$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#backdrop').onclick=closeCart;$('#modalClose').onclick=()=>$('#productModal').close();$('#searchBtn').onclick=()=>{$('#searchModal').showModal();setTimeout(()=>$('#searchInput').focus(),50)};$('#searchClose').onclick=()=>$('#searchModal').close();$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase().trim();const r=state.products.filter(p=>`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q));$('#searchResults').innerHTML=q?r.map(p=>`<div class="search-result" data-id="${p.id}"><span>${p.name}</span><b>${money(p.price)}</b></div>`).join(''):'';$$('.search-result').forEach(x=>x.onclick=()=>{$('#searchModal').close();openProduct(x.dataset.id)})};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderProducts()});$('#footerWhatsApp').href=waLink('Hi Sharif Store, I have a question.');renderCart();loadProducts();