/* Generated by scripts/build-products.mjs. Do not edit by hand. */
window.PRODUCTS_DATA=[
  {
    "id": "nb-530",
    "name": "New Balance 530",
    "brand": "New Balance",
    "price": 0,
    "new_drop": true,
    "sizes": [
      "37",
      "38",
      "39",
      "40",
      "41"
    ],
    "description": "Chunky everyday sneaker with a breathable upper. Choose your color and size.",
    "variants": {
      "Black / White": [
        "assets/products/IMG_0441.jpg",
        "assets/products/IMG_0447.png",
        "assets/products/IMG_0448.png",
        "assets/products/IMG_0450.png",
        "assets/products/IMG_0451.png"
      ],
      "White": [
        "assets/products/fast/white-variant/IMG_0427.webp",
        "assets/products/fast/white-variant/IMG_0428.webp",
        "assets/products/fast/white-variant/IMG_0430.webp",
        "assets/products/fast/white-variant/IMG_0432.webp",
        "assets/products/fast/white-variant/IMG_0433.webp",
        "assets/products/fast/white-variant/IMG_0441.webp",
        "assets/products/fast/white-variant/IMG_0443.webp",
        "assets/products/fast/white-variant/IMG_0444.webp",
        "assets/products/fast/white-variant/IMG_0447.webp",
        "assets/products/fast/white-variant/IMG_0448.webp",
        "assets/products/fast/white-variant/IMG_0450.webp",
        "assets/products/fast/white-variant/IMG_0451.webp"
      ]
    }
  },
  {
    "id": "nb-aero-runner",
    "name": "New Balance Aero Runner",
    "brand": "New Balance",
    "price": 0,
    "new_drop": true,
    "sizes": [
      "37",
      "38",
      "39",
      "40",
      "41"
    ],
    "description": "A sculpted performance-inspired runner with a cushioned statement sole and layered mesh upper.",
    "variants": {
      "Black / White": [
        "assets/products/fast/aero-runner/black-white/IMG_0454.webp",
        "assets/products/fast/aero-runner/black-white/IMG_0455.webp",
        "assets/products/fast/aero-runner/black-white/IMG_0456.webp",
        "assets/products/fast/aero-runner/black-white/IMG_0457.webp",
        "assets/products/fast/aero-runner/black-white/IMG_0458.webp",
        "assets/products/fast/aero-runner/black-white/IMG_0459.webp"
      ],
      "Blue / White": [
        "assets/products/fast/aero-runner/blue-white/IMG_0460.webp",
        "assets/products/fast/aero-runner/blue-white/IMG_0463.webp"
      ],
      "White / Black": [
        "assets/products/fast/aero-runner/white-black/IMG_0464.webp",
        "assets/products/fast/aero-runner/white-black/IMG_0465.webp",
        "assets/products/fast/aero-runner/white-black/IMG_0467.webp",
        "assets/products/fast/aero-runner/white-black/IMG_0468.webp",
        "assets/products/fast/aero-runner/white-black/IMG_0469.webp"
      ]
    }
  }
];
